### ISSUE TITLE
Instructor Contribution not added, 

### ISSUE THREAD

**Issue by Code-Blender-7** [PawanJS/forkify#1]
The project that is made called forkify is originally created by Jonas Schmedtmann. 
The API for the project is also only for those who bought the course on udemy.

It is recommended to add the instructor contribution directly to the readme. And to make sure that the API key is hidden along with its site.

Clarifications~
https://www.udemy.com/course/the-complete-javascript-course/

**Comment by PawanJS** [comment]
@Code-Blender-7 As requested, I have added the contribution in the readme file.
